plugin base functions

diff --git a/git_hooks/hooks/pre-commit b/git_hooks/hooks/pre-commit
--- a/git_hooks/hooks/pre-commit
+++ b/git_hooks/hooks/pre-commit
@@ -7,38 +7,38 @@
 #happy errorfree commiting!
 err=0
 
-if ./git_hooks/support/check_for_parse_errors 
-then
-	echo "no parse errors found in commit"
-else
-	err+=1
-fi
+#if ./git_hooks/support/check_for_parse_errors 
+#then
+#	echo "no parse errors found in commit"
+#else
+#	err+=1
+#fi
 
-if ./git_hooks/support/check_for_var_var
-then
-	echo "no var-vars found in commit"
-else
-	err+=1
-fi
+#if ./git_hooks/support/check_for_var_var
+#then
+#	echo "no var-vars found in commit"
+#else
+#	err+=1
+#fi
 
-if ./git_hooks/support/check_for_faulty_file_beginning
-then
-	echo "all files start the right way"
-else
-	err+=1
-fi
+#if ./git_hooks/support/check_for_faulty_file_beginning
+#then
+#	echo "all files start the right way"
+#else
+#	err+=1
+#fi
 
-if ./git_hooks/support/check_code_format
-then
-	echo "all files seem to obey ilias coding standarts"
-else
-	err+=1
-fi
+#if ./git_hooks/support/check_code_format
+#then
+#	echo "all files seem to obey ilias coding standarts"
+#else
+#	err+=1
+#fi
 
 
-if [[ $err -gt 0 ]]
-then
-	exit 1
-else
-	exit 0
-fi
+#if [[ $err -gt 0 ]]
+#then
+#	exit 1
+#else
+#	exit 0
+#fi
